In [ ]:
import pandas as pd

loan = pd.read_csv(r'../CleanData/clean_loan.csv', sep=';')  # Berka files are usually semicolon-delimited
loan.head()
loan.info()
print(loan['account_id'].is_unique )
print(loan['loan_id'].is_unique)
# sanity check: at most one loan per account?

<class 'pandas.DataFrame'>
RangeIndex: 682 entries, 0 to 681
Data columns (total 9 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   loan_id     682 non-null    int64
 1   account_id  682 non-null    int64
 2   date        682 non-null    str
 3   amount      682 non-null    float64
 4   duration    682 non-null    int64
 5   payments    682 non-null    float64
 6   status      682 non-null    str
 7   target      682 non-null    int64
 8   is_closed   682 non-null    int64
dtypes: float64(2), int64(5), str(2)
memory usage: 48.1 KB
True
True

In [20]:
loan

,loan_id,account_id,date,amount,duration,payments,status,target,is_closed
0,5314,1787,1993-07-05,96396.0,12,8033.0,B,1,1
1,5316,1801,1993-07-11,165960.0,36,4610.0,A,0,1
2,6863,9188,1993-07-28,127080.0,60,2118.0,A,0,1
3,5325,1843,1993-08-03,105804.0,36,2939.0,A,0,1
4,7240,11013,1993-09-06,274740.0,60,4579.0,A,0,1
...,...,...,...,...,...,...,...,...,...
677,4989,105,1998-12-05,352704.0,48,7348.0,C,0,0
678,5221,1284,1998-12-05,52512.0,12,4376.0,C,0,0
679,6402,6922,1998-12-06,139488.0,24,5812.0,C,0,0
680,5346,1928,1998-12-06,55632.0,24,2318.0,C,0,0
681,6748,8645,1998-12-08,240900.0,60,4015.0,C,0,0

In [21]:
spine = loan[['loan_id', 'account_id', 'date', 'target']].copy()

spine = spine.rename(columns={
    'date': 'loan_date',
    'status': 'status_raw'   # renamed so nobody mistakes it for a usable feature
})

print(spine.shape)   # expect (682, 7)
assert spine['loan_id'].is_unique
assert spine.shape[0] == 682

(682, 4)

In [22]:
spine

     loan_id  account_id   loan_date  target
0       5314        1787  1993-07-05       1
1       5316        1801  1993-07-11       0
2       6863        9188  1993-07-28       0
3       5325        1843  1993-08-03       0
4       7240       11013  1993-09-06       0
..       ...         ...         ...     ...
677     4989         105  1998-12-05       0
678     5221        1284  1998-12-05       0
679     6402        6922  1998-12-06       0
680     5346        1928  1998-12-06       0
681     6748        8645  1998-12-08       0

[682 rows x 4 columns]

In [24]:
spine['target'].value_counts(normalize=True)

target
0    0.888563
1    0.111437
Name: proportion, dtype: float64